# Generated by Django 6.0.1 on 2026-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
