# Generated by Django 6.0.1 on 2026-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_produk_harga_alter_produk_id_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
